import { readdirSync, writeFileSync } from 'fs'
import { join, relative, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const appDir = join(__dirname, '..', 'app')
const outFile = join(__dirname, '..', 'lib', 'routes.ts')

const excludeDirs = new Set(['node_modules', '.next'])

function walk(dir) {
  const entries = readdirSync(dir, { withFileTypes: true })
  const pages = []

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (!excludeDirs.has(entry.name) && !entry.name.startsWith('_')) {
        pages.push(...walk(full))
      }
    } else if (entry.name === 'page.tsx' || entry.name === 'page.ts') {
      pages.push(full)
    }
  }

  return pages
}

function pathToRoute(filePath) {
  let route = relative(appDir, filePath)
  route = route.replace(/\\/g, '/')
  route = route.replace(/\/?page\.(tsx|ts)$/, '')
  if (route === 'index' || route === '') route = '/'
  else route = '/' + route
  return route
}

function routeToLabel(route) {
  if (route === '/') return 'Home'
  const segment = route.split('/').filter(Boolean).pop()
  return segment
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function generate() {
  const pageFiles = walk(appDir)
  const routeSet = new Set()

  const routes = pageFiles
    .map(f => pathToRoute(f))
    .filter(r => {
      if (routeSet.has(r)) return false
      routeSet.add(r)
      return true
    })
    .sort((a, b) => {
      if (a === '/') return -1
      if (b === '/') return 1
      return a.localeCompare(b)
    })
    .map(r => ({ path: r, label: routeToLabel(r) }))

  const content = `// Auto-generated by scripts/generate-routes.mjs — do not edit manually
export const routes = [
${routes.map(r => `  { path: '${r.path}', label: '${r.label}' }`).join(',\n')},
] as const
`

  writeFileSync(outFile, content, 'utf-8')
  console.log(`✓ Generated ${routes.length} routes → lib/routes.ts`)
}

generate()
