// Auto-generated by scripts/generate-routes.mjs — do not edit manually
export const routes = [
  { path: '/', label: 'Home' },
  { path: '/auth/login', label: 'Login' },
  { path: '/auth/register', label: 'Register' },
] as const
